разметка титульной страницы
htmlacademy-adaptive/1897333-pink-24 pull request #2
Opened 2021-12-16 20:55 UTC by shamozavr

2021-12-17 09:07 UTC, blckwltz requested changes

2021-12-17 09:07 UTC, blckwltz commented on source/index.html
> +        <img class="os-list__item--logo" src="img/.." alt="логотип Apple">
@shamozavr по БЭМ `--` добавляет модификатор. Модификаторы нужны, чтобы добавить какие-то дополнительные стили блоку или поменять существующие.
Примеры:
```
<h3 class="caption caption--small"></h3>

.caption {
  font-size: 30px;
}

.caption--small {
  font-size: 25px;
}
```

Здесь вместо `--` нужно использовать `-`. Нужно проверить, дальше во многих местах встречается аналогичная ошибка

2021-12-17 09:07 UTC, blckwltz commented on source/index.html
> +            А еще я познакомился со своей будущей женой в комментариях к выложенной фотографии!»</p>
@shamozavr заголовок и текст хорошо бы сделать элементами блока `reviews`

2021-12-17 09:07 UTC, blckwltz commented on source/index.html
> +          <img class="checked" src="img/.." alt="да">
@shamozavr для изображений тут вряд ли потребуются разные классы. Пока можно оставить, но удобнее будет сделать одинаковые, чтобы не повторять стили 2 раза

2021-12-17 09:07 UTC, blckwltz commented on source/index.html
> +    </div>
@shamozavr тут везде элементы блока `footer`, но самого блока нет

2021-12-18 10:00 UTC, shamozavr commented on source/index.html
> +          <li class="site-list__item">
поправил

2021-12-18 10:07 UTC, shamozavr commented on source/index.html
> +        <img class="os-list__item--logo" src="img/.." alt="логотип Apple">
поправил

2021-12-18 10:17 UTC, shamozavr commented on source/index.html
> +            А еще я познакомился со своей будущей женой в комментариях к выложенной фотографии!»</p>
обернул в <div class="reviews">

2021-12-18 10:22 UTC, shamozavr commented on source/index.html
> +          <img class="checked" src="img/.." alt="да">
точно... тупанул, заменил все на tariffs__cell--img

2021-12-18 10:35 UTC, shamozavr commented on source/index.html
> +    </div>
есть вроде
![image](https://user-images.githubusercontent.com/81470032/146638014-528cfda5-3e48-446f-820c-72017b3149be.png)

2021-12-21 19:01 UTC, blckwltz reviewed
@shamozavr по главной есть еще пара мелких правок, можно сделать вместе со следующим заданием

2021-12-21 19:01 UTC, blckwltz commented on source/index.html
> +            <p class="review">«Это приложение перевернуло мой мир и позволило по-новому взглянуть на привычные серые
@shamozavr заголовок и параграф хорошо бы сделать элементами блоками `reviews` (то есть `reviews__reviewer` и `reviews__review`, писал об этом в прошлый раз [тут](https://github.com/htmlacademy-adaptive/1897333-pink-24/pull/2#discussion_r771215805)). Обрати внимание, что сейчас у тебя блок `reviews` вложен сам в себя, так не должно быть

2021-12-21 19:01 UTC, merged