Module2 task2
htmlacademy-adaptive/1897333-pink-24 pull request #3
Opened 2021-12-21 19:20 UTC by shamozavr

разметка страниц с каталогом и формами

2021-12-22 18:46 UTC, blckwltz requested changes

2021-12-22 18:46 UTC, blckwltz commented on source/catalog.html
>      </div>
@shamozavr по каталогу:
- нужно заменить хедер, чтобы был как на остальных страницах, сейчас тут неисправленная версия
- пройтись по все м местам где есть `--` и заменить на один (`--` используются для модификаторов, писал об это в комментариях к прошлому заданию)

2021-12-22 18:46 UTC, blckwltz commented on source/form.html
> +        id="patronymic" required>
@shamozavr есть элементы блока `registration-data`, но самого блока нет

2021-12-22 18:46 UTC, blckwltz commented on source/form.html
> +        required>
@shamozavr аналогично, элементы блока `registration-data` без самого блока

2021-12-23 17:09 UTC, shamozavr commented on source/catalog.html
>      </div>
исправлено

2021-12-23 17:20 UTC, shamozavr commented on source/form.html
> +        id="patronymic" required>
поставил section class="registration-data"

2021-12-23 17:26 UTC, shamozavr commented on source/form.html
> +        required>
поставил section class="registration-data"

2021-12-23 19:31 UTC, merged