базовая стилизация всех страниц проекта
htmlacademy-adaptive/1897333-pink-24 pull request #5
Opened 2022-01-08 18:47 UTC by shamozavr

2022-01-09 15:54 UTC, blckwltz requested changes
@shamozavr со стилизацией на этом этапе все ОК.
Нужно проверить:

- имена классов с `--`, оставить их только там где это нужно, в остальных местах заменить на `-`
- правильно разделить все стили по файлам

2022-01-09 15:54 UTC, blckwltz commented on source/catalog.html
> +        <div class="card__photo--container">
@shamozavr здесь (и далее) снова ошибка с именованием. `--` используются только для модификаторов, при этом класс с модификатором не может использоваться без основного класса. Для разделения слов нужно использовать одиночный `-`

2022-01-09 15:54 UTC, blckwltz commented on source/catalog.html
> +            <img class="upload__instrument-crop-icon active" src="img/main_page/crop.svg" alt="обрезка" />
@shamozavr эти элементы по идее должны лейблами к соответствующим инпутам со скрытым текстом инлайновой svg внутри

2022-01-09 15:54 UTC, blckwltz commented on source/index.html
> +            <a class="main-nav__list-item" href="index.html">
@shamozavr кажется, что этот класс для ссылки лишний, так как он добавлен для li, в который она обернута

2022-01-09 15:54 UTC, blckwltz commented on source/less/catalog/catalog-intro.less
> +.catalog-main__header-wrapper {
@shamozavr как обсудили на консультации: для каждого БЭМ-блока должен быть отдельный стилевой файл, имя которого соответствует имени блока. В файле должны быть только стили этого блока и его элементов. 
То есть для `catalog-main` должен быть отдельный файл с аналогичным именем, а в этом должны остаться только стили для `catalog-intro`

2022-01-11 11:21 UTC, shamozavr commented on source/catalog.html
> +        <div class="card__photo--container">
убрал везде, оставил только
          <p class="card__photo--tag">Панорама дня</p>
![image](https://user-images.githubusercontent.com/81470032/148933699-3645049f-0208-456d-a7da-13505e336160.png)

2022-01-11 11:44 UTC, shamozavr commented on source/index.html
> +            <a class="main-nav__list-item" href="index.html">
исправил

2022-01-11 14:14 UTC, shamozavr commented on source/less/catalog/catalog-intro.less
> +.catalog-main__header-wrapper {
сделал всё кроме slidecontainer
как ни пытался переименовать класс чтобы в блок вписывался не получилось..
не пойму почему пока что..

2022-01-12 07:23 UTC, blckwltz requested changes

2022-01-12 07:23 UTC, blckwltz commented on source/catalog.html
> +          <p class="card__photo--tag">Панорама дня</p>
@shamozavr здесь тоже нужно поменять на `-`.
У тебя есть тег `img` с классом `card__photo`, допустим, у него такие стили:
```
.card__photo {
  width: 200px;
  height: 200px;
  object-fit: contain;
}
```
Обрати внимание, что первая карточка тянется не всю ширину, для изображения в ней как раз подойдет модификатор. Делаем так `<img class="card__photo card__photo--wide">`, стили будут выглядеть так:
```
.card__photo {
  width: 200px;
  height: 200px;
  object-fit: contain;
}

.card__photo--wide {
  width: 100%;
}
```
За счет модификатора мы сохраняем меняем одно свойство, при этом мы его используем вместе с основным классом, поэтому остальные стили сохраняем.

Для `card__photo--tag` будут совсем другие стили, поэтому это отдельная сущность – `card__photo-tag`

2022-01-12 07:23 UTC, blckwltz commented on source/less/catalog/feed.less
> +.card {
@shamozavr этот файл должен называться не `feed`, а `card` (так как в нем ты стилизуешь блок `card`)

2022-01-12 07:23 UTC, blckwltz commented on source/less/catalog/upload.less
> +}
@shamozavr эти стили нужно вынести в отдельный файл (`slider`), для того, что было правильно, `slidecontainer` можно переименовать в `slider__container`

2022-01-12 07:23 UTC, blckwltz commented on source/less/catalog/upload.less
> +  margin-top: 12px;
@shamozavr тут нужно переименовать классы в `upload__button-wrapper`, `upload__button-post` и `upload__button-cancel`, иначе получается, что это отдельные БЭМ-блоки, для которых должны быть свои файлы.

2022-01-12 07:23 UTC, blckwltz commented on source/less/form/feedback.less
> +}
@shamozavr `feedback-header` нужно переименовать в `feedback__header`, `input`, `select`, `textarea` стилизовать через каскад

2022-01-12 07:23 UTC, blckwltz commented on source/less/index/download.less
> +.download-description {
@shamozavr нужно переименовать в `download__button-wrapper`, `download__button` и `download__description` соответственно

2022-01-12 07:23 UTC, blckwltz commented on source/less/index/intro.less
> +.intro-wrapper {
@shamozavr нужно переименовать в `intro__wrapper`

2022-01-12 07:23 UTC, blckwltz commented on source/less/index/reviews.less
> +.review {
@shamozavr тут надо либо выносить в отдельные файлики, либо переименовать в `reviews__reviewer` и `reviews__review` (то есть сделать элементами блока `reviews`)

2022-01-19 17:21 UTC, shamozavr commented on source/less/catalog/feed.less
> +.card {
переименовал

2022-01-19 17:25 UTC, shamozavr commented on source/catalog.html
> +          <p class="card__photo--tag">Панорама дня</p>
изменил

2022-01-19 17:31 UTC, shamozavr commented on source/less/catalog/upload.less
> +}
перенес

2022-01-19 17:32 UTC, shamozavr commented on source/less/catalog/upload.less
> +  margin-top: 12px;
изменил

2022-01-19 17:35 UTC, shamozavr commented on source/less/form/feedback.less
> +}
не понял

2022-01-19 17:40 UTC, shamozavr commented on source/less/index/download.less
> +.download-description {
переименовал

2022-01-19 17:41 UTC, shamozavr commented on source/less/index/intro.less
> +.intro-wrapper {
переименовал

2022-01-19 17:55 UTC, shamozavr commented on source/less/index/reviews.less
> +.review {
сделал элементами блока reviews

2022-01-20 10:23 UTC, blckwltz reviewed
@shamozavr правки можно сделать вместе со следующим заданием

2022-01-20 10:23 UTC, blckwltz commented on source/less/form/os-choice.less
> +}
@shamozavr про селекторы по ID и `order` написал выше

2022-01-20 10:23 UTC, blckwltz commented on source/less/form/registration-data.less
> +.registration-data-wrapper {
@shamozavr нужно переименовать в `registration-data__wrapper`

2022-01-20 10:23 UTC, blckwltz commented on source/less/global/global.less
> +.page-main {
@shamozavr эти стили должны быть в отдельном файле

2022-01-20 10:23 UTC, blckwltz commented on source/less/global/global.less
> +.page__body {
@shamozavr тут нужно либо стилизовать по тегу `body`, либо добавить на `html` класс page (иначе ошибка по БЭМ получается)

2022-01-20 10:23 UTC, blckwltz commented on source/less/index/tariffs.less
> +.tariffs-wrapper {
@shamozavr переименовать в `tariffs__wrapper`

2022-01-20 10:23 UTC, blckwltz commented on source/index.html
> +      <a class="research-link" href="###">Узнать больше об исследовании</a>
@shamozavr здесь все классы должны быть через `__` (`research__timer` и т.д.), иначе получается, что это отдельные БЭМ-блоки

2022-01-20 10:24 UTC, merged